name: Publish packages to NPM
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@swissknife-api-components-nodejs"
      - name: Install dependencies
        run: yarn install
      - name: Check formatting
        run: yarn check-formatting
      - name: Build dependencies
        run: yarn compile
      - name: Add NPM auth token
        run: yarn config set -H "npmRegistries['//registry.npmjs.org'].npmAuthToken" ${{ secrets.API_COMPONENTS_NODEJS_NPM_RW_TOKEN }}
      - name: Publish package on NPM 📦
        run: yarn workspaces foreach --exclude swissknife-api-components-nodejs npm publish --tag="${{ github.ref_name }}" --access public --tag=latest
